version: '3'

services:

    nginx:
        build:
            context: ./docker/
            dockerfile: nginx.docker
        volumes:
            - ./app:/app
        depends_on:
            - php-fpm
        ports:
            - 8000:80

    php-fpm:
        build:
            context: ./docker/
            dockerfile: php-fpm.docker
        volumes:
            - ./app:/app
        depends_on:
            - mysql

    php-cli:
        build:
            context: ./docker/
            dockerfile: php-cli.docker
        volumes:
            - ./app:/app
        depends_on:
            - mysql

    mysql:
        image: mariadb:10.4
        ports:
            - 3366:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        volumes:
            - ./databases/mariadb:/var/lib/mysql
              
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - 8080:80
        environment:
            PMA_HOST: mysql
            PMA_USER: user
            PMA_PASSWORD: password

