version: '3'

services:

    nginx:
        build:
            context: ./docker/
            dockerfile: nginx.docker
        volumes:
            - ./app:/app
        depends_on:
            - php-fpm
        ports:
            - 8000:80

    php-fpm:
        build:
            context: ./docker/
            dockerfile: php-fpm.docker
        volumes:
            - ./app:/app

    php-cli:
        build:
            context: ./docker/
            dockerfile: php-cli.docker
        volumes:
            - ./app:/app
